//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flagr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flagr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF - AFGHANISTAN
        ///AL - ALBANIA
        ///DZ - ALGERIA
        ///AS - AMERICAN SAMOA
        ///AD - ANDORRA
        ///AO - ANGOLA
        ///AI - ANGUILLA
        ///AQ - ANTARCTICA
        ///AG - ANTIGUA AND BARBUDA
        ///AR - ARGENTINA
        ///AM - ARMENIA
        ///AW - ARUBA
        ///AU - AUSTRALIA
        ///AT - AUSTRIA
        ///AZ - AZERBAIJAN
        ///BS - BAHAMAS
        ///BH - BAHRAIN
        ///BD - BANGLADESH
        ///BB - BARBADOS
        ///BY - BELARUS
        ///BE - BELGIUM
        ///BZ - BELIZE
        ///BJ - BENIN
        ///BM - BERMUDA
        ///BT - BHUTAN
        ///BO - BOLIVIA
        ///BA - BOSNIA AND HERZEGOVINA
        ///BW - BOTSWANA
        ///BV - BOUVET ISLAND
        ///BR - BRAZIL
        ///IO - BRITISH INDIAN OCEAN TERRITORY
        ///BN  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryCodes {
            get {
                return ResourceManager.GetString("CountryCodes", resourceCulture);
            }
        }
    }
}
